<a href="https://colab.research.google.com/github/fengivan/Fluids-Lab/blob/master/xcgum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
from time import sleep


import pandas
import time
import sys
import threading

def getDeltaP(seconds): #returns the average deltaP over the last "seconds"
    filename = "editeddata.csv"
    header = ["Time", "P1", "P2", "P3", "P4", "AvgP1", "AvgP2", "AvgFlow", "AvgTemp", "CMFlow", "CMDensity", "CM Temp", "Freq Set"]
    useless = ["Time", "P1", "P2",  "AvgP1", "AvgP2", "AvgFlow", "AvgTemp","CMFlow",  "CMDensity", "CM Temp", "Freq Set"]
    size = sum(1 for l in open(filename))
    df=pd.read_csv(filename, skiprows=range(1, size -seconds*10), names = header)
   
    #df=pandas.read_csv("/home/pi/Desktop/Shared/Fluids-Lab/data", names = header)
    #df=(((df.tail(seconds*10+2)).head(seconds*10)).drop(useless,1)).astype(float)
    df=df.drop(useless,1).astype(float).tail(seconds*10)
    
    deltaP=df["P4"].mean()-df["P3"].mean()
    return df


def addxanthan(amount):  #adds "amount grams of xcgum to the tank"
    addtime=round((amount/.8775)+.7)
    stopAdd = threading.Timer(addtime, stop)
    #print("Adding "+str(addtime*.82)+ " grams of XC Gum over "+ str(addtime) + " seconds", file=writeTo)
    outputs.write_single(0,745)
    stopAdd.start()
    
def stop():
    outputs.write_single(0,0)
    
def stable(seconds):   #determines if the deltaP is stable over the past x seconds, criteria is no more than 1% of deltaP measurements have more than a 10% difference with the average over the past x seconds.
    header = ["Time", "P1", "P2", "P3", "P4", "AvgP1", "AvgP2", "AvgFlow", "AvgTemp", "CMFlow", "CMDensity", "CM Temp", "Freq Set"]
    useless = ["Time", "P1", "P2",  "AvgP1", "AvgP2", "AvgFlow", "AvgTemp","CMFlow",  "CMDensity", "CM Temp", "Freq Set"]

    df=pandas.read_csv("editeddata", names = header)
    df=(((df.tail(seconds*10+2)).head(seconds*10)).drop(useless,1)).astype(float)
    avg=df["P4"].mean()-df["P3"].mean()
    p1=df["P4"].tolist()
    p2=df["P3"].tolist()
    count=0
    print(len(p1))
    for i in range(0,len(p1)):
      if (p1[i]-p2[i])>avg*1.1 or (p1[i]-p2[i])<avg*.9:
        count=count+1
      
    if(count<seconds/10):
      return True
    return False


def maintain(setpoint, savefile):
  lastaddtime=time.time()
  startTime=time.time()
  while True:
    curDeltaP=getDeltaP(10)
    print (str(time.time()-startTime)+","+str(getDeltaP(10)), file = savefile)
    if curDeltaP<setpoint and stable(300) and (time.time()-lastaddtime)>300:
      addxanthan((setpoint-curDeltaP)/.0146)
      lastaddtime=time.time()
    savefile.flush()
    sleep(10)

In [32]:
getDeltaP(3)

    P3  P4
1  NaN NaN
2  NaN NaN
3  NaN NaN
4  NaN NaN
5  NaN NaN
6  NaN NaN
7  NaN NaN
8  NaN NaN
9  NaN NaN
10 NaN NaN
11 NaN NaN
12 NaN NaN
13 NaN NaN
14 NaN NaN
15 NaN NaN
16 NaN NaN
17 NaN NaN
18 NaN NaN
19 NaN NaN
20 NaN NaN
21 NaN NaN
22 NaN NaN
23 NaN NaN
24 NaN NaN
25 NaN NaN
26 NaN NaN
27 NaN NaN
28 NaN NaN
29 NaN NaN
30 NaN NaN